### ISSUE TITLE
Misleading badges

### ISSUE THREAD

**Issue by ankurk91** [meness/verifi#1]
All of the badges (packagist) in readme points to incorrect repos.

```
// Only travis-ci is correct
[![Travis](https://img.shields.io/travis/rust-lang/rust.svg)](https://travis-ci.org/meness/Verifi)
// Next badges are incorrect
[![Packagist](https://img.shields.io/packagist/dt/doctrine/orm.svg)](https://packagist.org/packages/meness/verifi)
[![Packagist](https://img.shields.io/packagist/v/symfony/symfony.svg)](https://packagist.org/packages/meness/verifi)
[![Packagist](https://img.shields.io/packagist/l/doctrine/orm.svg)](https://packagist.org/packages/meness/verifi)
```
I could not understand the reason behind it.
Please fix them. All you need to do is replace ```owner/repo```.

For example.
```
[![Packagist](https://img.shields.io/packagist/dt/meness/verifi.svg)](https://packagist.org/packages/meness/verifi)
```
Will render this - 
[![Packagist](https://img.shields.io/packagist/dt/meness/verifi.svg)](https://packagist.org/packages/meness/verifi)

**Comment by meness** [comment]
@ankurk91 I totally forgot, thanks for pointing that.

**Comment by the94air** [comment]
@meness `verifi` is a really nice piece of art. Thanks.
