### ISSUE TITLE
The config file is not getting published

### ISSUE THREAD

**Issue by the94air** [meness/verifi#5]
version 1.0.8
The only thing I get
```bash
$ php artisan vendor:publish --provider="Meness\Verifi\Providers\VerifiServiceProvider" --tag="config"
Publishing complete.
```
I should get
```bash
$ php artisan vendor:publish --provider="Meness\Verifi\Providers\VerifiServiceProvider" --tag="config"
Copied File [\vendor\meness\verifi\config\config.php] To [\config\verifi.php]
Publishing complete.
```
I can't find why this is happening,

## Update
Publishing the config file is working fine when running
```bash
$ php artisan vendor:publish
```
but not when publishing only the config file.

**Comment by meness** [comment]
@the94air I see, I don't think so this issue is related to this package because I have this problem with all packages while developing projects. `php artisan vendor:publish` always works.

@SelimSalihovic I hope you know something more about this.

**Comment by the94air** [comment]
Yea, the problem in the publish method. You forget to add the tag name. here a [PR](https://github.com/meness/verifi/pull/11)
