### ISSUE TITLE
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)

### ISSUE THREAD

**Issue by orlyapps** [meness/verifi#9]
Hi,

after the user registration i got the following error:

(1/1) FatalThrowableError
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
in Verifi.php (line 145)

I think this line is the problem ?
...
list('token' => $token, 'email' => $email, 'expiration' => $expiration) = $data;
...

Info:
Laravel 5.4
PHP Version 7.0.10
"meness/verifi": "^1.0",

Thanks
  Christian

**Comment by meness** [comment]
@orlyapps This package requires PHP 7.1 or greater. You need to update your PHP version. Look at [the composer](https://github.com/meness/verifi/blob/master/composer.json#L28).
